# Generated by Django 5.0.6 on 2024-05-31 06:18

import apps.galeria.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to=apps.galeria.models.path_dir)),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('publica', models.BooleanField(default=False)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('accesible_para', models.CharField(choices=[('todos', 'todos'), ('seleccionados', 'seleccionados')], default='seleccionados', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to=apps.galeria.models.path_dir)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to=apps.galeria.models.path_dir)),
            ],
        ),
    ]
