# Generated by Django 5.0.6 on 2024-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galeria', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_archivo', to='tags.tags'),
        ),
    ]
