# Generated by Django 5.0.6 on 2024-05-31 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galeria', '0002_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivo_nombre', to='galeria.carpeta'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_carpeta', to='galeria.carpeta'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_imagen', to='tags.tags'),
        ),
        migrations.AddField(
            model_name='video',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_carpeta', to='galeria.carpeta'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_video', to='tags.tags'),
        ),
    ]
