# Generated by Django 5.0.6 on 2024-06-03 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
