# Generated by Django 5.0.6 on 2024-05-31 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_administrativa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(related_name='curso_alumnos', to='curso.alumno'),
        ),
        migrations.AddField(
            model_name='curso',
            name='asignaturas',
            field=models.ManyToManyField(related_name='curso_asignaturas', to='curso.asignatura'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docentes',
            field=models.ManyToManyField(related_name='asignatura_docente', to='curso.docente'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_actividad', to='curso.actividad'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_alumno', to='curso.alumno'),
        ),
        migrations.AddField(
            model_name='docente',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docente_institucion', to='curso.institucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_institucion', to='curso.institucion'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura_institucion', to='curso.institucion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_institucion', to='curso.institucion'),
        ),
        migrations.AddField(
            model_name='administrativos',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrativo_institucion', to='curso.institucion'),
        ),
        migrations.AddField(
            model_name='planasignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_asignatura', to='curso.asignatura'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_plan', to='curso.planasignatura'),
        ),
    ]
