# Generated by Django 5.0.6 on 2024-06-03 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='matricula',
            field=models.IntegerField(default=1),
        ),
    ]
